spring:
  application:
    name: auth-todo
  datasource:
    url: jdbc:mysql://localhost:3306/task_manager
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret-key: my-secret-keymy-secret-keymy-secret-keymy-secret-keymy-secret-keymy-secret-key
  access-token-validity: 86400
  refresh-token-validity: 2592000
