name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle Wrapper 실행 권한 추가
      - name: Add execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      # 4. 프로젝트 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 5. 빌드 결과 확인 (디버깅용)
      - name: Check build output
        run: ls -la build/libs/

  dockerize-and-deploy:
    name: Dockerize and Deploy
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. JAR 파일 확인
      - name: Verify JAR file exists
        run: |
          if [ ! -f "build/libs/auth-todo-0.0.1-SNAPSHOT.jar" ]; then
            echo "JAR file not found! Exiting..."
            exit 1
          fi

      # 4. Docker 이미지 빌드
      - name: Build Docker Image
        run: docker build -t syhere/auth-todo-app:latest .

      # 5. Docker 이미지 푸시
      - name: Push Docker Image
        run: docker push syhere/auth-todo-app:latest

      # 6. AWS EC2에 배포
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull syhere/auth-todo-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 8080:8080 --name my-app \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://database-1.czs2e0qaqyw7.ap-northeast-2.rds.amazonaws.com:3306/test \
              -e SPRING_DATASOURCE_USERNAME=admin \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }} \
              syhere/auth-todo-app:latest
